lib/shop_test_web/router.ex
defmodule ShopTestWeb.Router do
  use ShopTestWeb, :router

  import ShopTestWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ShopTestWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ShopTestWeb do
    pipe_through :browser

    live "/products", ProductLive.Index, :index
    live "/products/:id", ProductLive.Show, :show

    live "/checkout", CheckoutLive.New, :index

    live "/", PageLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", ShopTestWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ShopTestWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", ShopTestWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated, :put_session_layout]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/login", UserSessionController, :new
    post "/users/login", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", ShopTestWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings/update_password", UserSettingsController, :update_password
    put "/users/settings/update_email", UserSettingsController, :update_email
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", ShopTestWeb do
    pipe_through [:browser]

    delete "/users/logout", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/shop_test_web/controllers/user_session_controller.ex
defmodule ShopTestWeb.UserSessionController do
  use ShopTestWeb, :controller

  alias ShopTest.Accounts
  alias ShopTestWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      UserAuth.login_user(conn, user, user_params)
    else
      render(conn, "new.html", error_message: "Invalid e-mail or password")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Logged out successfully.")
    |> UserAuth.logout_user()
  end
end

lib/shop_test_web/views/user_session_view.ex
defmodule ShopTestWeb.UserSessionView do
  use ShopTestWeb, :view
end

lib/shop_test_web/templates/user_session/new.html.eex
<h5 class="pb-2 px-5 text-lg leading-normal text-center">Login</h5>
<%= form_for @conn, Routes.user_session_path(@conn, :create), [as: :user], fn f -> %>
  <%= if @error_message do %>
    <div class="alert alert-danger">
      <small><%= @error_message %></small>
    </div>
  <% end %>

  <div class="mt-4 mb-4">
    <%= label f, :email, class: "tag-label" %>
    <%= text_input f, :email, required: true, class: "tag-input" %>
  </div>

  <div class="mb-4">
    <%= label f, :password, class: "tag-label" %>
    <%= password_input f, :password, required: true, class: "tag-input" %>
  </div>

  <%= label f, :remember_me, class: "tag-label" do %>
    <%= checkbox f, :remember_me, class: "tag-checkbox" %>
    <span class="ml-1">Keep me logged in for 60 days</span>
  <% end %>

  <div class="mt-6">
    <%= submit "Login", class: "btn btn-dark w-full" %>
  </div>
<% end %>

<div class="mt-3 text-center text-gray-600">
  <small>Already have an account?</small>
</div>

<div class="mt-3">
  <%= link "Register", to: Routes.user_registration_path(@conn, :new), class: "btn btn-link btn-sm" %>
  <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new), class: "btn btn-link btn-sm" %>
</div>