lib/shop_test_web/router.ex
defmodule ShopTestWeb.Router do
  use ShopTestWeb, :router

  import ShopTestWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ShopTestWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ShopTestWeb do
    pipe_through :browser

    live "/products", ProductLive.Index, :index
    live "/products/:id", ProductLive.Show, :show

    live "/checkout", CheckoutLive.New, :index

    live "/", PageLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", ShopTestWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ShopTestWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", ShopTestWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated, :put_session_layout]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/login", UserSessionController, :new
    post "/users/login", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", ShopTestWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings/update_password", UserSettingsController, :update_password
    put "/users/settings/update_email", UserSettingsController, :update_email
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", ShopTestWeb do
    pipe_through [:browser]

    delete "/users/logout", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/shop_test_web/views/layout_view.ex
defmodule ShopTestWeb.LayoutView do
  use ShopTestWeb, :view
end

lib/shop_test_web/templates/layout/_user_menu.html.eex
<%= if @current_user do %>
  <%= link "Settings", to: Routes.user_settings_path(@conn, :edit), class: "btn btn-sm btn-link" %>
  <%= link "Logout", to: Routes.user_session_path(@conn, :delete), method: :delete, class: "btn btn-sm btn-link" %>
<% else %>
  <%= link "Sign In", to: Routes.user_session_path(@conn, :new), class: "btn btn-sm btn-link" %>
  <%= link "Get Started", to: Routes.user_registration_path(@conn, :new), class: "btn btn-sm btn-primary" %>
<% end %>

lib/shop_test_web/templates/layout/app.html.eex
<main role="main" class="container mx-auto mb-8 px-4 max-w-6xl">
  <p class="alert alert-info alert-left toast" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger alert-left toast" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/shop_test_web/templates/layout/live.html.leex
<main role="main" class="container mx-auto mb-8 px-4 max-w-6xl">
  <p class="alert alert-success alert-left toast" role="alert"
    phx-click="lv:clear-flash"
    phx-hook="InitToast"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger alert-left toast" role="alert"
    phx-click="lv:clear-flash"
    phx-hook="InitToast"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

<%= if assigns[:live_action] in [:new, :edit] do %>
  <div class="z-40 fixed bg-blue-900 top-0 left-0 bottom-0 right-0 opacity-75"></div>
<% end %>

lib/shop_test_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="en" class="h-full">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "ShopTest", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body class="flex flex-col h-full bg-gray-100">
    <header class="z-30 fixed top-0 right-0 left-0 bg-white shadow px-2 sm:px-4 py-4">
      <div class="container mx-auto flex justify-between items-center">
        <a href="/" title="ShopTest Home Page" class="flex items-center text-xl text-gray-900">
          ShopTest
        </a>
        <div class="flex items-center space-x-1">
          <div class="hidden md:inline-flex space-x-1">
            <%= link "Home", to: Routes.page_path(@conn, :index), class: "btn btn-sm btn-link" %>
            <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
              <%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home), class: "btn btn-sm btn-link" %>
            <% end %>
          </div>
          <%= render "_user_menu.html", assigns %>
          <div class="inline-flex md:hidden" x-data="{ open: false }">
            <button class="btn btn-link btn-sm px-2 flex-none" @click="open = true">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                aria-hidden="true"
                >
                <line x1="3" y1="12" x2="21" y2="12"></line>
                <line x1="3" y1="6" x2="21" y2="6"></line>
                <line x1="3" y1="18" x2="21" y2="18"></line>
              </svg>
              <span class="sr-only">Open Menu</span>
            </button>
            <div class="flex flex-col space-y-3 absolute m-2 top-0 left-0 right-0 rounded bg-white z-50 p-2 pb-4 shadow" x-show.transition="open" @click.away="open = false" x-cloak>
              <button class="btn btn-link btn-icon px-2 ml-2 flex-none self-end" @click="open = false">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  aria-hidden="true"
                  >
                  <line x1="18" y1="6" x2="6" y2="18"></line>
                  <line x1="6" y1="6" x2="18" y2="18"></line>
                </svg>
                <span class="sr-only">Close Menu</span>
              </button>
              <%= link "Home", to: Routes.page_path(@conn, :index), class: "btn btn-link w-full" %>
              <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
                <%= link "LiveDashboard", to: Routes.live_dashboard_path(@conn, :home), class: "btn btn-link w-full" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </header>

    <%= @inner_content %>

    <footer class="footer bg-gray-800 text-gray-600 mt-auto py-6">
      <div class="container mx-auto px-4 max-w-6xl">
        <span class="text-muted">ShopTest</span>
      </div>
    </footer>
  </body>
</html>

lib/shop_test_web/templates/layout/session.html.eex
<!DOCTYPE html>
<html lang="en" class="h-full">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <%= live_title_tag assigns[:page_title] || "ShopTest", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body class="flex flex-col h-full bg-gray-700">
    <header>
      <nav class="flex flex-wrap items-center justify-between py-2 px-4 fixed top-0 right-0 left-0 z-30 bg-gray-700">
        <a class="inline-block mr-4 py-1 text-xl text-gray-300" href="#"><i class="fas fa-bolt"></i> ShopTest</a>
      </nav>
    </header>

    <main role="main" class="container mx-auto mb-8 px-4 max-w-6xl">
      <p class="alert alert-info alert-left toast" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger alert-left toast" role="alert"><%= get_flash(@conn, :error) %></p>

      <div class="flex justify-center p-2">
        <div class="card w-full max-w-xs">
          <div class="card-body">
            <%= @inner_content %>
          </div>
        </div>
      </div>
    </main>

    <footer class="footer bg-gray-800 text-gray-600 mt-auto py-6">
      <div class="container mx-auto px-4 max-w-6xl">
        <span class="text-muted">ShopTest</span>
      </div>
    </footer>
  </body>
</html>